import type { Metadata } from 'next';
import {
  Poppins,
  Allison,
  Playfair_Display,
  Montserrat,
} from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

const allison = Allison({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-allison',
});

const playfair_display = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-playfair-display',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.variable} ${allison.variable} ${playfair_display.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
